doctrine:
    dbal:
        default_connection:       default
        connections:
            default:
                dbname:           '%env(resolve:DATABASE_NAME)%'
                user:             root
                password:         null
                host:             "%env(resolve:DATABASE_HOST)%"
                port:             "%env(resolve:DATABASE_PORT)%"
                server_version:   '8.3'
            oppressed:
                dbname:           '%env(resolve:DATABASE_NAME)%'
                user:             oppressed
                password:         NZGWYUW98CQLUXAE
                host:             "%env(resolve:DATABASE_HOST)%"
                port:             "%env(resolve:DATABASE_PORT)%"
                server_version:   '8.3'
            customer:
                dbname:           '%env(resolve:DATABASE_NAME)%'
                user:             customer
                password:         KNa8MWjnaukb8tcY
                host:             "%env(resolve:DATABASE_HOST)%"
                port:             "%env(resolve:DATABASE_PORT)%"
                server_version:   '8.3'
            salesperson:
                dbname:           '%env(resolve:DATABASE_NAME)%'
                user:             salesperson
                password:         dWCP3M6wPpCFwdEa
                host:             "%env(resolve:DATABASE_HOST)%"
                port:             "%env(resolve:DATABASE_PORT)%"
                server_version:   '8.3'
            moderator:
                dbname:           '%env(resolve:DATABASE_NAME)%'
                user:             mod
                password:         DNxnS2eRRkHe8nbY
                host:             "%env(resolve:DATABASE_HOST)%"
                port:             "%env(resolve:DATABASE_PORT)%"
                server_version:   '8.3'
            admin:
                dbname:           '%env(resolve:DATABASE_NAME)%'
                user:             admin
                password:         URhwXtwZ34FsB5Hs
                host:             "%env(resolve:DATABASE_HOST)%"
                port:             "%env(resolve:DATABASE_PORT)%"
                server_version:   '8.3'
        # url: '%env(resolve:DATABASE_URL)%'
        
        # Deprecated type, never use enumerations
        # types:
        #     enumnation: 'App\DBAL\EnumNationType' #Change it to valid class

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '16'

        # profiling_collect_backtrace: '%kernel.debug%'
        # use_savepoints: true
    orm:
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                mappings:
                    Main:
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: Main
            customer:
                connection: customer
                mappings:
                    Customer:
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: Customer
            salesperson:
                connection: salesperson
                mappings:
                    Salesperson:
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: Salesperson
            moderator:
                connection: moderator
                mappings:
                    Moderator:
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: Moderator

        # auto_generate_proxy_classes: true
        # enable_lazy_ghost_objects: true
        # report_fields_where_declared: true
        # validate_xml_mapping: true
        # naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        # auto_mapping: true
        # mappings:
        #     App:
        #         type: attribute
        #         is_bundle: false
        #         dir: '%kernel.project_dir%/src/Entity'
        #         prefix: 'App\Entity'
        #         alias: App
        # controller_resolver:
        #     auto_mapping: false

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
